### ISSUE TITLE
Redmine 2.6 shows 500 internal server error for My Account page when this plugin is installed.

### ISSUE THREAD

**Issue by dbeckham** [jrupesh/redmine_my_page#18]
In Redmine 2.6, when going to the "My Account" page at `/my/account`, I receive a 500 internal server error. Uninstalling the plugin restores the My Account page.

The error message from `production.log`:

```
Completed 500 Internal Server Error in 63.3ms

ActionView::Template::Error (wrong number of arguments (2 for 1)):
    41: <fieldset class="box tabular">
    42:   <legend><%=l(:label_preferences)%></legend>
    43:   <%= render :partial => 'users/preferences' %>
    44:   <%= call_hook(:view_my_account_preferences, :user => @user, :form => f) %>
    45: </fieldset>
    46:
    47: </div>
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:158:in `call_hook'
  app/views/my/account.html.erb:44:in `block in _app_views_my_account_html_erb__3582855195318000207_47398840'
  app/helpers/application_helper.rb:1056:in `labelled_form_for'
  app/views/my/account.html.erb:9:in `_app_views_my_account_html_erb__3582855195318000207_47398840'
```

**Comment by royceking** [comment]
+1 I get the same error when going to /my/account.

**Comment by jrupesh** [comment]
Hi Guys,
Can you let me know the ruby and rails version?
Thanks.

**Comment by royceking** [comment]
redmine]$ rails -v
Rails 3.2.21
