### ISSUE TITLE
internal error after deleting "all" query

### ISSUE THREAD

**Issue by TonyRideBike** [jrupesh/redmine_my_page#39]
Dear Rupesh,

I'd like to firstly thank you for creating this useful plugin!

I deleted one query of "all" and then the plugin caused an error with this log:

```
Started GET "/redmine/my/page" for 14.26.73.224 at 2018-01-19 11:35:09 +0800
Processing by MyController#page as HTML
  Current user: tony.lyu (id=7)
  Rendered my/blocks/_issue_query_selection.html.erb (1.1ms)
  Rendered queries/_columns.html.erb (1.2ms)
  Rendered my/blocks/_issues.erb (4.7ms)
  Rendered plugins/redmine_my_page/app/views/my/_my_page_activities.html.erb (2.2ms)
  Rendered plugins/redmine_my_page/app/views/my/blocks/_activities.html.erb (2.5ms)
  Rendered my/page.html.erb within layouts/base (24.4ms)
Completed 500 Internal Server Error in 32ms (ActiveRecord: 8.0ms)

ActionView::Template::Error (undefined method `project_id' for nil:NilClass):
    18: 
    19:   <script type="text/javascript">
    20:     $.ajax({
    21:         url: "<%= query.project_id.nil? ? activity_path(:query_id => query_id) :
    22:                   project_activity_path( :id => query.project_id, :query_id => query_id ) %>",
    23:         cache: false,
    24:         success: function(html){$("#my-activities-"+ "<%= query_id %>").append(html);},
  plugins/redmine_my_page/app/views/my/_my_page_activities.html.erb:21:in `_plugins_redmine_my_page_app_views_my__my_page_activities_html_erb__1365772282778660569_70308165411940'
  plugins/redmine_my_page/app/views/my/blocks/_activities.html.erb:20:in `block in _plugins_redmine_my_page_app_views_my_blocks__activities_html_erb__3348487005950010121_70308165359160'
  plugins/redmine_my_page/app/views/my/blocks/_activities.html.erb:19:in `each'
  plugins/redmine_my_page/app/views/my/blocks/_activities.html.erb:19:in `_plugins_redmine_my_page_app_views_my_blocks__activities_html_erb__3348487005950010121_70308165359160'
  app/helpers/my_helper.rb:58:in `render_block_content'
  app/helpers/my_helper.rb:35:in `render_block'
  app/helpers/my_helper.rb:27:in `block in render_blocks'
  app/helpers/my_helper.rb:26:in `each'
  app/helpers/my_helper.rb:26:in `render_blocks'
  app/views/my/page.html.erb:13:in `block in _app_views_my_page_html_erb__1804990256705747609_70308149419160'
  app/views/my/page.html.erb:11:in `each'
  app/views/my/page.html.erb:11:in `_app_views_my_page_html_erb__1804990256705747609_70308149419160'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```
it might not be a bug in this plugin but I really need a solution, can you help on this?

**Comment by TonyRideBike** [comment]
Really helped! thank you!
