### ISSUE TITLE
Redmine 4 support?

### ISSUE THREAD

**Issue by vsc55** [jrupesh/redmine_my_page#42]
are there any plans to fix it for redmine 4?

now it show's error:

```
# bundle exec rake redmine:plugins:migrate RAILS_ENV=production
NoMethodError: undefined method `to_prepare' for ActionDispatch::Callbacks:Class
Did you mean?  to_param
/opt/redmine/redmine-4.0/plugins/redmine_my_page/init.rb:7:in `<top (required)>'
/usr/local/lib64/ruby/gems/2.4.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
/usr/local/lib64/ruby/gems/2.4.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/lib64/ruby/gems/2.4.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/lib64/ruby/gems/2.4.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
/opt/redmine/redmine-4.0/lib/redmine/plugin.rb:173:in `block in load'
/opt/redmine/redmine-4.0/lib/redmine/plugin.rb:164:in `each'
/opt/redmine/redmine-4.0/lib/redmine/plugin.rb:164:in `load'
/opt/redmine/redmine-4.0/config/initializers/30-redmine.rb:21:in `<top (required)>'
/usr/local/lib64/ruby/gems/2.4.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `load'
/usr/local/lib64/ruby/gems/2.4.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `block in load'
/usr/local/lib64/ruby/gems/2.4.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/lib64/ruby/gems/2.4.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `load'
/usr/local/lib64/ruby/gems/2.4.0/gems/railties-5.2.2/lib/rails/engine.rb:657:in `block in load_config_initializer'
/usr/local/lib64/ruby/gems/2.4.0/gems/activesupport-5.2.2/lib/active_support/notifications.rb:170:in `instrument'
/usr/local/lib64/ruby/gems/2.4.0/gems/railties-5.2.2/lib/rails/engine.rb:656:in `load_config_initializer'
/usr/local/lib64/ruby/gems/2.4.0/gems/railties-5.2.2/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
/usr/local/lib64/ruby/gems/2.4.0/gems/railties-5.2.2/lib/rails/engine.rb:613:in `each'
/usr/local/lib64/ruby/gems/2.4.0/gems/railties-5.2.2/lib/rails/engine.rb:613:in `block in <class:Engine>'
/usr/local/lib64/ruby/gems/2.4.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/lib64/ruby/gems/2.4.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
/usr/local/lib64/ruby/gems/2.4.0/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/lib64/ruby/gems/2.4.0/gems/railties-5.2.2/lib/rails/initializable.rb:50:in `each'
/usr/local/lib64/ruby/gems/2.4.0/gems/railties-5.2.2/lib/rails/initializable.rb:50:in `tsort_each_child'
/usr/local/lib64/ruby/gems/2.4.0/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/lib64/ruby/gems/2.4.0/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
/opt/redmine/redmine-4.0/config/environment.rb:14:in `<top (required)>'
/usr/local/lib64/ruby/gems/2.4.0/gems/railties-5.2.2/lib/rails/application.rb:337:in `require'
/usr/local/lib64/ruby/gems/2.4.0/gems/railties-5.2.2/lib/rails/application.rb:337:in `require_environment!'
/usr/local/lib64/ruby/gems/2.4.0/gems/railties-5.2.2/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/usr/local/lib64/ruby/gems/2.4.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

```

**Comment by saytik** [comment]
> NoMethodError: undefined method `to_prepare' for ActionDispatch::Callbacks:Class

replace ActionDispatch::Callbacks:Class.to_prepare with  ActiveSupport::Reloader.to_prepare
in file plugins/redmine_my_page/init.rb

**Comment by vsc55** [comment]
Thank saytik for you info. 👍 
I used the commit fix:
https://github.com/bizyman/redmine_my_page/commit/d9c256ff253cfd5611b8fe0227556cb22b482db3
