### ISSUE TITLE
Activity tab cannot be displayed

### ISSUE THREAD

**Issue by pskokovic** [jrupesh/redmine_my_page#47]
**Description:**
After adding _redmine_my_page_ plugin to Redmine it is not possible to access the Activity tab. 

**Log shows the following lines:**
```
Started GET "/activity" for 192.168.32.104 at 2020-06-17 15:26:51 +0200
Processing by ActivitiesController#index as HTML
  Current user: predrag.skokovic (id=5)
Completed 500 Internal Server Error in 88ms (ActiveRecord: 21.0ms)

NameError (undefined local variable or method `index_without_esi' for #<ActivitiesController:0x000055bcc62cd908>
Did you mean?  index_with_esi):

plugins/redmine_my_page/lib/my_page_patches/activities_controller_patch.rb:87:in `index_with_esi'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
```

```
Environment:
    Redmine version                4.1.1.stable
    Ruby version                   2.5.1-p57 (2018-03-29) [x86_64-linux-gnu]
    Rails version                  5.2.4.2
    Environment                    production
    Database adapter               Mysql2
    Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
    Mailer delivery                smtp
SCM:
    Git                            2.17.1
    Filesystem                     
Redmine plugins:
    external_links_in_new_window   0.9
    redmine_my_page                0.1.13
```

**Comment by agh1** [comment]
I'm experiencing the same problem:

```
  Redmine version                4.1.1.stable
  Ruby version                   2.6.6-p146 (2020-03-31) [x86_64-linux]
  Rails version                  5.2.4.2
  Environment                    production
  Database adapter               PostgreSQL
```

**Comment by fujexo** [comment]
We have the same issue in our installation

**Comment by winged** [comment]
Happens if "Enable Activity listing in MyPage" is disabled. So as a workaround, you can enable that setting to avoid the HTTP/500
